[package]
name = "exchange-lab-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
once_cell.workspace = true
prometheus.workspace = true
thiserror.workspace = true
