[package]
name = "exchange-lab-journal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
crc32fast.workspace = true
exchange-lab-core = { path = "../core" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
